---
title: "Factorial Models, Kronecker Products, and Interaction Terms"
author: "Doug Hemken"
date: "November 22, 2018"
output:
  html_document: default
  pdf_document: default
---

## Interaction Terms and Factorial Models

We may consider a model that includes only the mean of the response as a zero-order model,
sometimes called an intercept-only model.
A model with means of several categories, parameterized as a mean and offsets to that mean,
is a model with multiple intercepts (only), and is also a zero-order model.  Classical
ANOVA models are zero-order models.

A model of a response with a continuous variable includes both an intercept and a slope.
This is a first-order model, with a zero-order term and a first-order term.  Adding
categorical variables to the model adds more intercepts, or zero-order terms.  Adding
continuous variables adds more slopes, or first-order terms.  Such additive models
are first-order models.

An interaction term is formed as the product of two variables.  A product of categorical
variables adds intercepts to the model.  The interaction of a categorical variable and
a continuous variable adds slopes to the model.  In either case, the order of the model
remains the same.  But the interaction formed from the product of two continuous variables
adds a second-order term to a model, a curvature.

A factorial model is formed by adding all the products of all the zero- and first-order
terms, in all combinations.  If we think of the terms in a model as its column space, then
any linear model resides in a subspace of the factorial column space.  The columns of any 
linear model are a subset of the columns in a full-factorial model.

### An Example, Two Variables

Consider three models

- $y = b_0 + b_1x$, also expressed in matrix form as $y = Xb$
- $y = c_0 + c_1z$, or $y=Zc$
- $y = d_0 + d_1x +d_2z + d_3xz$, or $y=Ad$

The column space a $A$ may be formed as an outer product of the column spaces of
$X$ and $Z$.  Denote $X = [\begin{array} & 1_x & x \end{array}]$ and
$Z = [\begin{array} & 1_z & z \end{array}]$.  Then
$$X \otimes Z = [\begin{array} & 1_x & x \end{array}] \otimes[\begin{array} & 1_z & z \end{array}]$$
This operation produces a matrix with the correct column space of $A$. 
$$[\begin{array} & 1_x1_z & 1_xz &x1_z & xz \end{array}]=[\begin{array} & 1 & z &x & xz \end{array}]$$
(However, our row space is a subset of the outer product of the rows, which are also
produced by any Kronecker operation.  So the model matrix for a model with interaction
terms is a submatrix of the Kronecker product(s) of the zero- and first-order terms.  The
full Kronecker product becomes useful in the design of experiments, see Vartak.)