source("mean.to.matrix.r")
source("sd.to.matrix.r")
source("colSds.r")
source("kron.r")
source("clean.kron.names.r")
source("terms.vars.degrees.r")
source("poly.to.interaction.r")  # sub-routine for  poly.fix()
source("poly.fix.r")
source("polyterm.r")
# source("matching.terms.r")     # deprecated
source("match.terms.r")
source("clean.order.r")
source("recentering.matrix.r")   # same as matrix.build.clean.r
source("factor.direct.sum.r")
source("collect.terms.r")
source("ref.to.gm.r")
source("pastex.r")
source("generate.all.terms.r")
source("poly.lower.fill.r")